apiVersion: v1
kind: ReplicationController
metadata:
  name: clamav
  labels:
    name: clamav
spec:
  replicas: 1
  selector:
    name: clamav
  template:
    metadata:
      labels:
        name: clamav
    spec:
      volumes:
      - name: avdata
        emptyDir: {}
      containers:
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy:v1.1.6
        imagePullPolicy: Always
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8080'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
        ports:
         - name: https
           containerPort: 443
        resources:
         limits:
          cpu: 200m
          memory: 400M
      - name: clamd-rest
        image: quay.io/gileshinchcliff/clamav-rest:test 
        imagePullPolicy: Always
        env:
        - name: HOST
          value: localhost
        - name: PORT
          value: '3310'
        ports:
        - containerPort: 8080
          name: api
          protocol: TCP
        
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 300
          timeoutSeconds: 2
        resources:
         limits:
          cpu: 800m
          memory: 800M
      - name: clamd
        image: quay.io/gileshinchcliff/clamav:testing
        imagePullPolicy: Always
        env:
        - name: UPDATE
          value: "false"
        ports:
        - containerPort: 3310
          name: api
          protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/clamav
            name: avdata
        livenessProbe:
          exec:
            command:
            - /readyness.sh
          initialDelaySeconds: 20
          timeoutSeconds: 2
        resources:
         limits:
          cpu: 200m
          memory: 400M
      - name: freshclam
        image: quay.io/gileshinchcliff/clamav:testing
        imagePullPolicy: Always
        env:
        - name: UPDATE_ONLY
          value: "true"
        volumeMounts:
        - mountPath: /var/lib/clamav
          name: avdata
        livenessProbe:
          exec:
            command:
            - /readyness.sh
          initialDelaySeconds: 20
          timeoutSeconds: 2
        resources:
         limits:
          cpu: 100m
          memory: 400M
