apiVersion: v1
kind: ReplicationController
metadata:
  name: clamav
  labels:
    name: clamav
spec:
  replicas: 1
  selector:
    name: clamav
  template:
    metadata:
      labels:
        name: clamav
    spec:
      containers:
      - name: clamd
        image: quay.io/ukhomeofficedigital/clamav:v0.1.0rc2
        env:
        - name: UPDATE
          value: "false"
        ports:
        - containerPort: 3200
          name: api
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/clamav
          name: avdata
      - name: freshclam
        image: quay.io/ukhomeofficedigital/clamav:v0.1.0rc2
        env:
        - name: UPDATE_ONLY
          value: "true"
        volumeMounts:
        - mountPath: /var/lib/clamav
          name: avdata
      volumes:
      - name: avdata
        source:
          emptyDir: {}
